### ISSUE TITLE
Not finding Ble server

### ISSUE THREAD

**Issue by AleksaA21** [IRNAS/IRNAS-ble-app#4]
Thanks for this peace of code guys, it seems great.

Sadly, I have issues when scanning for devices. Polidea function "this.manager.startDeviceScan" seems to not find my ESP32 sometimes(almost always). Do you have any idea about why this could happen?

Also, did you fix this:
TODO fix ReferenceError: Can't find variable: device (screenshot na P10)

I am testing the app with your Uart-profile branch code.

**Comment by SloMusti** [comment]
@AleksaA21 can you please provide more details about the setup and also an example code to flash on ESP32. This may give us a change to test and debug more easily.

**Comment by AleksaA21** [comment]
[BLE_WIFI.zip](https://github.com/IRNAS/IRNAS-ble-app/files/5034529/BLE_WIFI.zip)

This is my esp32 project. Basically esp32 is set up as GATT server. I've edited the service, rx, and tx characteristics in react native code. I found it twice last night, and was able to send custom messages(that's what i needed). But now it just won't find it.

**Comment by AleksaA21** [comment]
I use react-native 0.63.2. React-native-cli is 2.0.1

**Comment by AleksaA21** [comment]
It worked once again today. What in the world would make the app find it once, but not each time?

**Comment by AleksaA21** [comment]
Yo vid553 bro, any help here?

**Comment by SloMusti** [comment]
@AleksaA21 our team will review this issue, subject to availability. Given that supporting this codebase is not part of our commercial offering, the responses may be somewhat delayed. Your patience is appreciated.

**Comment by AleksaA21** [comment]
Thanks a lot for your response. Sorry for me being impatient. 
It's a fine app, the best rn app I've found on github. Was really sad that I didn't have luck to make it work 100%. 
It scans some other devices 100%. But with esp32, it's really bad, weird.

**Comment by AleksaA21** [comment]
It fixed itself today. Nothing was changed. Thanks guys
